### ISSUE TITLE
Error while getting duration

### ISSUE THREAD

**Issue by shubham0804** [caffco/get-video-duration#74]
Hi. I have been able to successfully use this library on Windows but on Ubuntu, I'm getting the follow error: 

`1|Message-Server  | 2021-05-09T17:57:39: Error: Command failed with exit code 1: /Dev/node_modules/@ffprobe-installer/l                    inux-x64/ffprobe -v error -show_format -show_streams https://cdn.fbsbx.com/v/t59.3654-21/183098887_524357068578588_8345053379644033323_n.mp                    4/audioclip-1620563256000-1649.mp4?_nc_cat=100&ccb=1-3&_nc_sid=7272a8&_nc_ohc=Ys1YiHg8JcMAX82ghZI&_nc_ht=cdn.fbsbx.com&oh=055b7559cce4efcac                    c5630e854936d47&oe=60995445
1|Message-Server  | 2021-05-09T17:57:39: https://cdn.fbsbx.com/v/t59.3654-21/183098887_524357068578588_8345053379644033323_n.mp4/audioclip-                    1620563256000-1649.mp4?_nc_cat=100&ccb=1-3&_nc_sid=7272a8&_nc_ohc=Ys1YiHg8JcMAX82ghZI&_nc_ht=cdn.fbsbx.com&oh=055b7559cce4efcacc5630e854936                    d47&oe=60995445: Resource temporarily unavailable
1|Message-Server  | 2021-05-09T17:57:39:     at makeError (/Dev/node_modules/execa/lib/error.js:59:11)
1|Message-Server  | 2021-05-09T17:57:39:     at handlePromise (/Dev/node_modules/execa/index.js:114:26)
1|Message-Server  | 2021-05-09T17:57:39:     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
1|Message-Server  | 2021-05-09T17:57:39:   shortMessage: 'Command failed with exit code 1: /Dev/node_modules/@ffprobe-i                    nstaller/linux-x64/ffprobe -v error -show_format -show_streams https://cdn.fbsbx.com/v/t59.3654-21/183098887_524357068578588_83450533796440                    33323_n.mp4/audioclip-1620563256000-1649.mp4?_nc_cat=100&ccb=1-3&_nc_sid=7272a8&_nc_ohc=Ys1YiHg8JcMAX82ghZI&_nc_ht=cdn.fbsbx.com&oh=055b755                    9cce4efcacc5630e854936d47&oe=60995445',
1|Message-Server  | 2021-05-09T17:57:39:   command: '/Dev/node_modules/@ffprobe-installer/linux-x64/ffprobe -v error -s                    how_format -show_streams https://cdn.fbsbx.com/v/t59.3654-21/183098887_524357068578588_8345053379644033323_n.mp4/audioclip-1620563256000-16                    49.mp4?_nc_cat=100&ccb=1-3&_nc_sid=7272a8&_nc_ohc=Ys1YiHg8JcMAX82ghZI&_nc_ht=cdn.fbsbx.com&oh=055b7559cce4efcacc5630e854936d47&oe=60995445'                    ,
1|Message-Server  | 2021-05-09T17:57:39:   exitCode: 1,
1|Message-Server  | 2021-05-09T17:57:39:   signal: undefined,
1|Message-Server  | 2021-05-09T17:57:39:   signalDescription: undefined,
1|Message-Server  | 2021-05-09T17:57:39:   stdout: '',
1|Message-Server  | 2021-05-09T17:57:39:   stderr: 'https://cdn.fbsbx.com/v/t59.3654-21/183098887_524357068578588_8345053379644033323_n.mp4                    /audioclip-1620563256000-1649.mp4?_nc_cat=100&ccb=1-3&_nc_sid=7272a8&_nc_ohc=Ys1YiHg8JcMAX82ghZI&_nc_ht=cdn.fbsbx.com&oh=055b7559cce4efcacc                    5630e854936d47&oe=60995445: Resource temporarily unavailable',
1|Message-Server  | 2021-05-09T17:57:39:   failed: true,
1|Message-Server  | 2021-05-09T17:57:39:   timedOut: false,
1|Message-Server  | 2021-05-09T17:57:39:   isCanceled: false,
1|Message-Server  | 2021-05-09T17:57:39:   killed: false
1|Message-Server  | 2021-05-09T17:57:39: }
`

Running `ffmpeg -version` gives the following output:
`ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
`

The url is valid. Could you please help me out.

**Comment by shubham0804** [comment]
The library is working on the Ubuntu machine but doesn't seem to work with fb urls. But the library gets the duration for the same url in my Windows machine.

Url: `https://cdn.fbsbx.com/v/t59.3654-21/183778543_244749240739493_7434004898709928944_n.mp4/audioclip-1620571602000-9474.mp4?_nc_cat=109&ccb=1-3&_nc_sid=7272a8&_nc_ohc=V3Tl0HeC_TMAX-a9TAn&_nc_ht=cdn.fbsbx.com&oh=52d7df0bad563d0dd5179cd65a3d651a&oe=609998F5`

**Comment by Sumolari** [comment]
Are you using the same version of Nodejs in both machines?
Have you tried using ffprobe directly?

This library is just wrapping calls to ffprobe, it doesn't fetch the URL directly but relies on ffprobe doing that.

**Comment by shubham0804** [comment]
The Node versions are pretty much the same v14.15.0 on Windows and v14.15.5 on Ubuntu through nvm.

I haven't tried ffprobe directly, but have come up with a workaround wherein I download the file locally using:

```
async function downloadVideo(url) {
    const path = Path.resolve(__dirname, "files", randomFileName);
    const writer = Fs.createWriteStream(path);
    const response = await Axios({
        url,
        method: "GET",
        responseType: "stream",
    });
    response.data.pipe(writer);
    return new Promise((resolve, reject) => {
        writer.on("finish", resolve(path));
        writer.on("error", reject);
    });
}
```
Then I call `getVideoDurationInSeconds` to get the duration. But for some reason, this worked  sometimes and sometimes it didn't. I added a 100ms setTimeout between downloading the video using the above function and calling `getVideoDurationInSeconds` and it seems to work till now.

```
const timer = () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve("okay");
        }, 100);
    });
};
```

I know this is not the right solution, but I have been stuck on this since yesterday & I can't come up with a better one. There is probably something wrong with the file returned by Facebook or the download function above (found on StackOverflow).

@Sumolari If you could provide some insight on the above code or something else, I would really appreciate it, else you may close this issue. Thanks for this library!

p.s the error which led me to add the setTimeout was:
```
1|Message-Server  | 2021-05-10T12:33:50: Error: Command failed with exit code 1: /Messenger/Dev/node_modules/@ffprobe-installer/linux-x64/ffprobe -v error -show_format -show_streams /Messenger/Dev/files/WzgtJbb.mp4
1|Message-Server  | 2021-05-10T12:33:50: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x6956b00] moov atom not found
1|Message-Server  | 2021-05-10T12:33:50: /Messenger/Dev/files/WzgtJbb.mp4: Invalid data found when processing input
1|Message-Server  | 2021-05-10T12:33:50:     at makeError (/Messenger/Dev/node_modules/execa/lib/error.js:59:11)
1|Message-Server  | 2021-05-10T12:33:50:     at handlePromise (/Messenger/Dev/node_modules/execa/index.js:114:26)
1|Message-Server  | 2021-05-10T12:33:50:     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
1|Message-Server  | 2021-05-10T12:33:50:   shortMessage: 'Command failed with exit code 1: /Messenger/Dev/node_modules/@ffprobe-installer/linux-x64/ffprobe -v error -show_format -show_streams /Messenger/Dev/files/WzgtJbb.mp4',
1|Message-Server  | 2021-05-10T12:33:50:   command: '/Messenger/Dev/node_modules/@ffprobe-installer/linux-x64/ffprobe -v error -show_format -show_streams /Messenger/Dev/files/WzgtJbb.mp4',
1|Message-Server  | 2021-05-10T12:33:50:   exitCode: 1,
1|Message-Server  | 2021-05-10T12:33:50:   signal: undefined,
1|Message-Server  | 2021-05-10T12:33:50:   signalDescription: undefined,
1|Message-Server  | 2021-05-10T12:33:50:   stdout: '',
1|Message-Server  | 2021-05-10T12:33:50:   stderr: '[mov,mp4,m4a,3gp,3g2,mj2 @ 0x6956b00] moov atom not found\n' +
1|Message-Server  | 2021-05-10T12:33:50:     '/Messenger/Dev/files/WzgtJbb.mp4: Invalid data found when processing input',
1|Message-Server  | 2021-05-10T12:33:50:   failed: true,
1|Message-Server  | 2021-05-10T12:33:50:   timedOut: false,
1|Message-Server  | 2021-05-10T12:33:50:   isCanceled: false,
1|Message-Server  | 2021-05-10T12:33:50:   killed: false
1|Message-Server  | 2021-05-10T12:33:50: }

```

**Comment by Sumolari** [comment]
It could be useful to know the user agent sent by ffprobe vs axios, maybe Facebook is filtering based on that and that's why it's not failing in Windows or when using axios.

**Comment by Sumolari** [comment]
Closing due to inactivity
